apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: webapp-rs
spec:
  selector:
    matchLabels:
      mylabelname: webapp
  replicas: 2
  template:
    metadata:
      labels:
        mylabelname: webapp
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---

apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    mylabelname: queue
spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1
